### ISSUE TITLE
Create `to-upstream` branch

### ISSUE THREAD

**Issue by Grissess** [jrddunbr/ElectricalAge#121]
The current comparison (as of this writing) between `base` and `upstream/develop` is as follows:

    Showing 326 changed files with 31,198 additions and 16,596 deletions.

The longer we wait, the harder it's going to be to manage this divergence.

Let's start unifying `base` and `upstream` into a "cold" branch--I propose `to-upstream`. Absolutely no commits should be done directly on this branch; it should represent a _portion_ of the changes on the way from `upstream/develop` to `base`, with changes picked from `base` as needed.

The intent is mainly to make the unification process more pleasant for upstream, and eventually converge our development efforts.

Since we have a lot of "beta level" features, those should probably go last on the order. Let's start with the ones that we've tested more thoroughly--chronological order is convenient.

For now, our fork will remain unique in its feature set, and won't dissolve anytime soon--let's just focus on giving back to upstream when we can :)

In approximate order:

- [ ] Signal Bus Cable
- [ ] Shaft Rewrite
  - [ ] New "basic" objects (Motor)
  - [ ] Basic ShaftPart refactor
  - [ ] New objects (clutch, fixed shaft)
- [ ] Config Copy Tool
- [ ] Working Power Sockets
- [ ] ~New alarms~ (still working on it)
- [ ] ~Sound rewrite~ (@jrddunbr's working on it)

In no particular order:

- [ ] Minutiae
  - [ ] Sound system fixes
  - [ ] Colored data loggers
  - [ ] Fixed logger printouts
  - [ ] New icons
  - [ ] Cancellable grid wiring
  - [ ] Wireless distance caching?

**Comment by jrddunbr** [comment]
I think we're just going to re-implement (cherry pick) everything in the 1.12 branch and not merge into 1.7.10 on the main repository, since Baughn isn't continuing 1.7.10 much, if at all. The 1.12 mod is going to have so many changes we are going to be mostly re-writing everything anyways - or so it should be at least.

**Comment by jrddunbr** [comment]
This issue is being closed now since there will be no more feature updates in Electrical Age for Minecraft 1.7.10.
If the issue is relevant to 1.12, it will be re-opened there at a later date.
